import { Business, User, Appointment, LoyaltyReward, City, DashboardStats } from './types'

const PH = '/placeholder-business.svg'
const AV = '/placeholder-avatar.svg'

export const CITIES: City[] = [
  { id: 'nairobi', name: 'Nairobi', country: 'Kenya', currency: 'KES', currencySymbol: 'KSh' },
  { id: 'kampala', name: 'Kampala', country: 'Uganda', currency: 'UGX', currencySymbol: 'USh' },
  { id: 'dar-es-salaam', name: 'Dar es Salaam', country: 'Tanzania', currency: 'TZS', currencySymbol: 'TSh' },
  { id: 'lagos', name: 'Lagos', country: 'Nigeria', currency: 'NGN', currencySymbol: '₦' },
  { id: 'accra', name: 'Accra', country: 'Ghana', currency: 'GHS', currencySymbol: 'GH₵' },
]

export const CURRENT_USER: User = {
  id: 'u1',
  name: 'Amara Okonkwo',
  email: 'amara@example.com',
  phone: '+254 712 345 678',
  avatar: AV,
  role: 'customer',
  city: 'nairobi',
  loyaltyPoints: 2450,
  loyaltyTier: 'silver',
  joinedAt: '2025-03-15',
  totalBookings: 18,
}

export const BUSINESSES: Business[] = [
  {
    id: 'b1',
    name: 'Crown Cuts Barbershop',
    type: 'barbershop',
    description: 'Premium grooming experience in the heart of Westlands. Our master barbers have over 15 years of combined experience crafting the perfect fade, taper, and beard styles. We specialize in modern African gentleman aesthetics.',
    shortDescription: 'Premium fades & beard grooming in Westlands',
    coverImage: '/images/stitch/barber.jpg',
    galleryImages: [PH, PH, PH, PH],
    logo: PH,
    badge: 'elite',
    rating: 4.9,
    reviewCount: 312,
    address: 'Westgate Mall, Westlands',
    city: 'nairobi',
    neighborhood: 'Westlands',
    coordinates: { lat: -1.2646, lng: 36.8068 },
    distance: 1.2,
    phone: '+254 701 234 567',
    email: 'crowncuts@example.com',
    services: [
      { id: 's1', name: 'Classic Fade', category: 'haircut', description: 'Clean skin fade with scissor work on top', price: 800, duration: 45, popular: true },
      { id: 's2', name: 'Premium Fade + Beard Line Up', category: 'beard', description: 'Full groom package: fade + beard sculpt', price: 1400, duration: 75, popular: true },
      { id: 's3', name: 'Taper Cut', category: 'haircut', description: 'Classic taper with clean edges', price: 700, duration: 40, popular: false },
      { id: 's4', name: 'Afro Shape Up', category: 'haircut', description: 'Shape and define your natural afro', price: 600, duration: 35, popular: false },
      { id: 's5', name: 'Beard Trim & Shape', category: 'beard', description: 'Precision beard sculpting', price: 500, duration: 30, popular: false },
      { id: 's6', name: 'Hot Towel Shave', category: 'beard', description: 'Traditional straight razor shave with hot towel treatment', price: 1200, duration: 60, popular: true },
    ],
    staff: [
      { id: 'st1', name: 'James Kariuki', avatar: AV, role: 'Master Barber', specialties: ['haircut', 'beard'], rating: 4.9, reviewCount: 156, available: true },
      { id: 'st2', name: 'Michael Otieno', avatar: AV, role: 'Senior Barber', specialties: ['haircut', 'haircut'], rating: 4.8, reviewCount: 98, available: true },
      { id: 'st3', name: 'David Njoroge', avatar: AV, role: 'Barber', specialties: ['haircut', 'beard'], rating: 4.7, reviewCount: 58, available: false },
    ],
    reviews: [
      { id: 'r1', userId: 'u2', userName: 'Brian Mwangi', userAvatar: AV, rating: 5, comment: 'James is an absolute legend. Best fade I\'ve had in Nairobi. The hot towel shave is next level. Will never go anywhere else.', date: '2026-05-28', serviceReceived: 'Premium Fade + Beard Line Up', staffName: 'James Kariuki' },
      { id: 'r2', userId: 'u3', userName: 'Kevin Omuya', userAvatar: AV, rating: 5, comment: 'Impeccable service, great ambiance, worth every shilling. Michael shaped me up perfectly for my wedding.', date: '2026-05-20', serviceReceived: 'Classic Fade', staffName: 'Michael Otieno' },
      { id: 'r3', userId: 'u4', userName: 'Alex Kamau', userAvatar: AV, rating: 4, comment: 'Consistently great cuts. Booking is easy through the app. The loyalty points are a nice bonus.', date: '2026-05-15', serviceReceived: 'Taper Cut', staffName: 'James Kariuki' },
    ],
    hours: {
      monday: { open: '08:00', close: '20:00', closed: false },
      tuesday: { open: '08:00', close: '20:00', closed: false },
      wednesday: { open: '08:00', close: '20:00', closed: false },
      thursday: { open: '08:00', close: '20:00', closed: false },
      friday: { open: '08:00', close: '21:00', closed: false },
      saturday: { open: '07:00', close: '21:00', closed: false },
      sunday: { open: '09:00', close: '18:00', closed: false },
    },
    amenities: ['Free WiFi', 'Air Conditioning', 'Card Payment', 'M-Pesa', 'Complimentary Drinks', 'Parking'],
    priceRange: '$$',
    isOpen: true,
    waitTime: 15,
    nextAvailable: '2:30 PM Today',
    totalBookings: 4580,
    repeatCustomerRate: 78,
    responseTime: '< 5 min',
    planTier: 'elite',
    joinedAt: '2024-01-15',
    featured: true,
    tags: ['Popular', 'Top Rated', 'Walk-ins Welcome'],
  },
  {
    id: 'b2',
    name: 'Luxe Beauty Lounge',
    type: 'hair_salon',
    description: 'Nairobi\'s premier luxury hair salon for the modern African woman. Specialists in natural hair, braids, weaves, and color treatments. Our stylists trained in Johannesburg, Lagos, and London.',
    shortDescription: 'Luxury natural hair & styling sanctuary',
    coverImage: '/images/stitch/braiding.jpg',
    galleryImages: [PH, PH, PH, PH],
    logo: PH,
    badge: 'premium',
    rating: 4.8,
    reviewCount: 487,
    address: 'The Hub Karen, Karen',
    city: 'nairobi',
    neighborhood: 'Karen',
    coordinates: { lat: -1.3197, lng: 36.7118 },
    distance: 8.4,
    phone: '+254 722 567 890',
    email: 'luxebeauty@example.com',
    services: [
      { id: 's7', name: 'Box Braids (Medium)', category: 'braiding', description: 'Protective medium box braids with extension hair', price: 4500, duration: 300, popular: true },
      { id: 's8', name: 'Knotless Braids', category: 'braiding', description: 'Lightweight knotless braids, scalp-friendly', price: 5500, duration: 360, popular: true },
      { id: 's9', name: 'Full Weave Install', category: 'weave', description: 'Sew-in weave with leave-out styling', price: 6000, duration: 240, popular: false },
      { id: 's10', name: 'Silk Press', category: 'hair_styling', description: 'Professional silk press for natural hair', price: 2500, duration: 120, popular: true },
      { id: 's11', name: 'Hair Color (Full)', category: 'color', description: 'Full hair coloring with premium products', price: 7000, duration: 180, popular: false },
      { id: 's12', name: 'Natural Hair Treatment', category: 'hair_styling', description: 'Deep conditioning and protein treatment', price: 1800, duration: 90, popular: false },
    ],
    staff: [
      { id: 'st4', name: 'Grace Wanjiku', avatar: AV, role: 'Lead Stylist', specialties: ['braiding', 'hair_styling', 'color'], rating: 4.9, reviewCount: 234, available: true },
      { id: 'st5', name: 'Faith Achieng', avatar: AV, role: 'Braiding Specialist', specialties: ['braiding', 'locs'], rating: 4.8, reviewCount: 178, available: false },
      { id: 'st6', name: 'Stella Muthoni', avatar: AV, role: 'Color Technician', specialties: ['color', 'hair_styling'], rating: 4.7, reviewCount: 75, available: true },
    ],
    reviews: [
      { id: 'r4', userId: 'u5', userName: 'Patricia Ndege', userAvatar: AV, rating: 5, comment: 'Grace is hands down the best braider in Nairobi. My knotless braids lasted 8 weeks and still looked fresh. The salon is so clean and luxurious.', date: '2026-05-25', serviceReceived: 'Knotless Braids', staffName: 'Grace Wanjiku' },
      { id: 'r5', userId: 'u6', userName: 'Mercy Waweru', userAvatar: AV, rating: 5, comment: 'Worth every single shilling. Came for a silk press and left feeling like a queen. Already booked my next appointment.', date: '2026-05-18', serviceReceived: 'Silk Press', staffName: 'Grace Wanjiku' },
    ],
    hours: {
      monday: { open: '09:00', close: '19:00', closed: false },
      tuesday: { open: '09:00', close: '19:00', closed: false },
      wednesday: { open: '09:00', close: '19:00', closed: false },
      thursday: { open: '09:00', close: '19:00', closed: false },
      friday: { open: '09:00', close: '20:00', closed: false },
      saturday: { open: '08:00', close: '20:00', closed: false },
      sunday: { open: '10:00', close: '17:00', closed: false },
    },
    amenities: ['Free WiFi', 'Air Conditioning', 'Card Payment', 'M-Pesa', 'Refreshments', 'TV Entertainment', 'Kids Corner'],
    priceRange: '$$$',
    isOpen: true,
    waitTime: undefined,
    nextAvailable: 'Tomorrow 10:00 AM',
    totalBookings: 8920,
    repeatCustomerRate: 85,
    responseTime: '< 10 min',
    planTier: 'premium',
    joinedAt: '2023-08-20',
    featured: true,
    tags: ['Luxury', 'Natural Hair', 'By Appointment'],
  },
  {
    id: 'b3',
    name: 'Glam Nail Studio',
    type: 'nail_studio',
    description: 'Nail artistry at its finest. Gel, acrylic, nail art, and express manis. Using only top-tier brands — OPI, CND, Gelish.',
    shortDescription: 'Premium nail art & gel services',
    coverImage: PH,
    galleryImages: [PH, PH],
    logo: PH,
    badge: 'verified',
    rating: 4.7,
    reviewCount: 203,
    address: 'Yaya Centre, Hurlingham',
    city: 'nairobi',
    neighborhood: 'Hurlingham',
    coordinates: { lat: -1.2891, lng: 36.7937 },
    distance: 3.1,
    phone: '+254 733 890 123',
    email: 'glamnails@example.com',
    services: [
      { id: 's13', name: 'Gel Manicure', category: 'nails', description: 'Long-lasting gel polish manicure', price: 1200, duration: 60, popular: true },
      { id: 's14', name: 'Acrylic Full Set', category: 'nails', description: 'Full acrylic nail set with your choice of shape', price: 2500, duration: 90, popular: true },
      { id: 's15', name: 'Nail Art (per nail)', category: 'nails', description: 'Custom nail art designs', price: 200, duration: 15, popular: false },
      { id: 's16', name: 'Pedicure + Gel', category: 'nails', description: 'Luxury pedicure with gel polish', price: 1800, duration: 75, popular: true },
    ],
    staff: [
      { id: 'st7', name: 'Lydia Kamau', avatar: AV, role: 'Lead Nail Technician', specialties: ['nails'], rating: 4.8, reviewCount: 145, available: true },
    ],
    reviews: [
      { id: 'r6', userId: 'u7', userName: 'Sandra Onyango', userAvatar: AV, rating: 5, comment: 'Lydia is an artist! My nails looked incredible for 4 weeks. The studio is so clean and professional.', date: '2026-05-22', serviceReceived: 'Acrylic Full Set', staffName: 'Lydia Kamau' },
    ],
    hours: {
      monday: { open: '09:00', close: '18:00', closed: false },
      tuesday: { open: '09:00', close: '18:00', closed: false },
      wednesday: { open: '09:00', close: '18:00', closed: false },
      thursday: { open: '09:00', close: '18:00', closed: false },
      friday: { open: '09:00', close: '19:00', closed: false },
      saturday: { open: '09:00', close: '19:00', closed: false },
      sunday: { open: '10:00', close: '16:00', closed: false },
    },
    amenities: ['Air Conditioning', 'M-Pesa', 'Card Payment', 'Free WiFi'],
    priceRange: '$$',
    isOpen: true,
    waitTime: 0,
    nextAvailable: 'Now',
    totalBookings: 2340,
    repeatCustomerRate: 71,
    responseTime: '< 15 min',
    planTier: 'premium',
    joinedAt: '2024-06-01',
    featured: false,
    tags: ['Walk-ins Welcome', 'Nail Art Specialists'],
  },
  {
    id: 'b4',
    name: 'Brushwork Makeup Studio',
    type: 'makeup_studio',
    description: 'Professional makeup for weddings, events, photoshoots, and everyday glam. Airbrush specialists.',
    shortDescription: 'Wedding & event makeup artistry',
    coverImage: '/images/stitch/skincare.jpg',
    galleryImages: [],
    logo: PH,
    badge: 'premium',
    rating: 4.9,
    reviewCount: 156,
    address: 'ABC Place, Westlands',
    city: 'nairobi',
    neighborhood: 'Westlands',
    coordinates: { lat: -1.2607, lng: 36.8016 },
    distance: 1.8,
    phone: '+254 744 567 234',
    email: 'brushwork@example.com',
    services: [
      { id: 's17', name: 'Bridal Makeup', category: 'makeup', description: 'Full bridal glam with trial session', price: 15000, duration: 180, popular: true },
      { id: 's18', name: 'Event Makeup', category: 'makeup', description: 'Stunning look for any special occasion', price: 4500, duration: 90, popular: true },
      { id: 's19', name: 'Airbrush Makeup', category: 'makeup', description: 'Flawless finish with airbrush technique', price: 6000, duration: 90, popular: false },
    ],
    staff: [
      { id: 'st8', name: 'Zara Hassan', avatar: AV, role: 'Lead MUA', specialties: ['makeup'], rating: 5.0, reviewCount: 156, available: true },
    ],
    reviews: [],
    hours: {
      monday: { open: '08:00', close: '18:00', closed: false },
      tuesday: { open: '08:00', close: '18:00', closed: false },
      wednesday: { open: '08:00', close: '18:00', closed: false },
      thursday: { open: '08:00', close: '18:00', closed: false },
      friday: { open: '08:00', close: '20:00', closed: false },
      saturday: { open: '07:00', close: '20:00', closed: false },
      sunday: { open: '07:00', close: '20:00', closed: false },
    },
    amenities: ['Air Conditioning', 'Card Payment', 'M-Pesa', 'Free WiFi'],
    priceRange: '$$$',
    isOpen: true,
    nextAvailable: 'Tomorrow 9:00 AM',
    totalBookings: 1820,
    repeatCustomerRate: 88,
    responseTime: '< 30 min',
    planTier: 'elite',
    joinedAt: '2024-02-10',
    featured: true,
    tags: ['Wedding Specialist', 'Highly Rated'],
  },
]

export const RECENT_APPOINTMENTS: Appointment[] = [
  {
    id: 'a1',
    customerId: 'u1',
    customerName: 'Amara Okonkwo',
    customerAvatar: AV,
    businessId: 'b1',
    businessName: 'Crown Cuts Barbershop',
    staffId: 'st1',
    staffName: 'James Kariuki',
    serviceId: 's1',
    serviceName: 'Classic Fade',
    servicePrice: 800,
    serviceDuration: 45,
    date: '2026-06-05',
    time: '10:00 AM',
    status: 'confirmed',
    paymentMethod: 'M-Pesa',
    loyaltyPointsEarned: 80,
  },
  {
    id: 'a2',
    customerId: 'u1',
    customerName: 'Amara Okonkwo',
    customerAvatar: AV,
    businessId: 'b2',
    businessName: 'Luxe Beauty Lounge',
    staffId: 'st4',
    staffName: 'Grace Wanjiku',
    serviceId: 's8',
    serviceName: 'Knotless Braids',
    servicePrice: 5500,
    serviceDuration: 360,
    date: '2026-05-20',
    time: '9:00 AM',
    status: 'completed',
    paymentMethod: 'Card',
    loyaltyPointsEarned: 550,
  },
  {
    id: 'a3',
    customerId: 'u1',
    customerName: 'Amara Okonkwo',
    customerAvatar: AV,
    businessId: 'b3',
    businessName: 'Glam Nail Studio',
    staffId: 'st7',
    staffName: 'Lydia Kamau',
    serviceId: 's14',
    serviceName: 'Acrylic Full Set',
    servicePrice: 2500,
    serviceDuration: 90,
    date: '2026-05-10',
    time: '2:00 PM',
    status: 'completed',
    paymentMethod: 'M-Pesa',
    loyaltyPointsEarned: 250,
  },
]

export const LOYALTY_REWARDS: LoyaltyReward[] = [
  {
    id: 'lr1',
    name: '20% Off Next Visit',
    description: 'Get 20% off your next booking at any Vantara partner salon',
    pointsCost: 500,
    value: '20% Discount',
    category: 'discount',
    image: PH,
    available: true,
  },
  {
    id: 'lr2',
    name: 'Free Classic Fade',
    description: 'Redeem for a complimentary Classic Fade at any partner barbershop',
    pointsCost: 1000,
    value: 'Free Service',
    category: 'free_service',
    businessName: 'Crown Cuts Barbershop',
    image: PH,
    available: true,
  },
  {
    id: 'lr3',
    name: 'VIP Priority Booking',
    description: 'Skip the wait — guaranteed next-slot priority booking for 30 days',
    pointsCost: 2000,
    value: '30-Day VIP',
    category: 'vip_access',
    image: PH,
    available: true,
  },
  {
    id: 'lr4',
    name: 'Complimentary Gel Manicure',
    description: 'Enjoy a free gel manicure at Glam Nail Studio',
    pointsCost: 1500,
    value: 'Free Service',
    category: 'free_service',
    businessName: 'Glam Nail Studio',
    image: PH,
    available: false,
  },
]

export const DASHBOARD_STATS: DashboardStats = {
  todayBookings: 12,
  todayRevenue: 18600,
  newCustomers: 3,
  pendingBookings: 4,
  weeklyRevenue: [14200, 16800, 12400, 19200, 18600, 22400, 15800],
  topServices: [
    { name: 'Classic Fade', count: 48, revenue: 38400 },
    { name: 'Premium Fade + Beard', count: 32, revenue: 44800 },
    { name: 'Hot Towel Shave', count: 18, revenue: 21600 },
    { name: 'Taper Cut', count: 14, revenue: 9800 },
  ],
  customerSatisfaction: 4.9,
  completionRate: 96,
}

export const TODAYS_APPOINTMENTS: Appointment[] = [
  {
    id: 'ta1',
    customerId: 'u8',
    customerName: 'Brian Mwangi',
    customerAvatar: AV,
    businessId: 'b1',
    businessName: 'Crown Cuts',
    staffId: 'st1',
    staffName: 'James Kariuki',
    serviceId: 's2',
    serviceName: 'Premium Fade + Beard',
    servicePrice: 1400,
    serviceDuration: 75,
    date: '2026-06-01',
    time: '9:00 AM',
    status: 'completed',
  },
  {
    id: 'ta2',
    customerId: 'u9',
    customerName: 'Kevin Omuya',
    customerAvatar: AV,
    businessId: 'b1',
    businessName: 'Crown Cuts',
    staffId: 'st2',
    staffName: 'Michael Otieno',
    serviceId: 's1',
    serviceName: 'Classic Fade',
    servicePrice: 800,
    serviceDuration: 45,
    date: '2026-06-01',
    time: '10:30 AM',
    status: 'in_progress',
  },
  {
    id: 'ta3',
    customerId: 'u10',
    customerName: 'Alex Kamau',
    customerAvatar: AV,
    businessId: 'b1',
    businessName: 'Crown Cuts',
    staffId: 'st1',
    staffName: 'James Kariuki',
    serviceId: 's6',
    serviceName: 'Hot Towel Shave',
    servicePrice: 1200,
    serviceDuration: 60,
    date: '2026-06-01',
    time: '2:00 PM',
    status: 'confirmed',
  },
  {
    id: 'ta4',
    customerId: 'u11',
    customerName: 'Peter Njiru',
    customerAvatar: AV,
    businessId: 'b1',
    businessName: 'Crown Cuts',
    staffId: 'st3',
    staffName: 'David Njoroge',
    serviceId: 's3',
    serviceName: 'Taper Cut',
    servicePrice: 700,
    serviceDuration: 40,
    date: '2026-06-01',
    time: '3:30 PM',
    status: 'pending',
  },
]
